// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANngXCVEuDSIc9XyDnzg0SH9obOs_QYOo',
    appId: '1:242386649251:android:5fd1c93544d4c9ffdfff16',
    messagingSenderId: '242386649251',
    projectId: 'finanzapp-final',
    storageBucket: 'finanzapp-final.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYweqQXPFnIBQgQKpNPA-F_9LEnUA2Xk0',
    appId: '1:242386649251:web:6874969b616ba4b4dfff16',
    messagingSenderId: '242386649251',
    projectId: 'finanzapp-final',
    authDomain: 'finanzapp-final.firebaseapp.com',
    storageBucket: 'finanzapp-final.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7AtLNTuF53c5BGP1qIq1aDCzKAjEVe1E',
    appId: '1:242386649251:ios:1b9a91c380b535dcdfff16',
    messagingSenderId: '242386649251',
    projectId: 'finanzapp-final',
    storageBucket: 'finanzapp-final.appspot.com',
    iosBundleId: 'com.example.finanzappFinal',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7AtLNTuF53c5BGP1qIq1aDCzKAjEVe1E',
    appId: '1:242386649251:ios:1b9a91c380b535dcdfff16',
    messagingSenderId: '242386649251',
    projectId: 'finanzapp-final',
    storageBucket: 'finanzapp-final.appspot.com',
    iosBundleId: 'com.example.finanzappFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYweqQXPFnIBQgQKpNPA-F_9LEnUA2Xk0',
    appId: '1:242386649251:web:77db24732d46eb39dfff16',
    messagingSenderId: '242386649251',
    projectId: 'finanzapp-final',
    authDomain: 'finanzapp-final.firebaseapp.com',
    storageBucket: 'finanzapp-final.appspot.com',
  );

}